# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Swift sürümü ayarla (Firebase SDK uyumluluğu için)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Swift 6.0 özelliklerini devre dışı bırak
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      # Swift 6.0 strict concurrency'yi devre dışı bırak
      config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'targeted'
      # Swift 6.0 language mode'u devre dışı bırak
      config.build_settings['SWIFT_LANGUAGE_VERSION'] = '5.9'
      # Swift 6.0 experimental features'ı devre dışı bırak
      config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xfrontend -disable-implicit-concurrency-module-import -Xfrontend -disable-implicit-string-processing-module-import -Xfrontend -warn-concurrency'
    end
  end
  
  # FirebaseCoreInternal için özel ayarlar - Swift 6.0 özelliklerini devre dışı bırak
  installer.pods_project.targets.each do |target|
    if target.name.include?('Firebase')
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.9'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'targeted'
        config.build_settings['SWIFT_LANGUAGE_VERSION'] = '5.9'
        # Swift 6.0 özelliklerini tamamen devre dışı bırak
        config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xfrontend -disable-implicit-concurrency-module-import -Xfrontend -disable-implicit-string-processing-module-import -Xfrontend -warn-concurrency -Xfrontend -disable-region-based-isolation'
      end
    end
  end
end
